// Central IPC registrar (mirrors the old routes/index.js): each feature module registers its own
// ipcMain.handle channels. Called once from electron/main.js before the BrowserWindow loads, so
// every channel exists before the renderer can invoke one.
const registerAccounts = require('./accounts.ipc');
const registerAccountClasses = require('./accountClasses.ipc');
const registerAlerts = require('./alerts.ipc');
const registerAuth = require('./auth.ipc');
const registerAddas = require('./addas.ipc');
const registerBackup = require('./backup.ipc');
const registerBankAccounts = require('./bankAccounts.ipc');
const registerBusinessAccounts = require('./businessAccounts.ipc');
const registerCategories = require('./categories.ipc');
const registerChartAccounts = require('./chartAccounts.ipc');
const registerCheques = require('./cheques.ipc');
const registerCities = require('./cities.ipc');
const registerCustomers = require('./customers.ipc');
const registerDraftPurchases = require('./draftPurchases.ipc');
const registerDraftPurchaseReturns = require('./draftPurchaseReturns.ipc');
const registerDraftExpenses = require('./draftExpenses.ipc');
const registerDraftReceipts = require('./draftReceipts.ipc');
const registerDraftSaleBills = require('./draftSaleBills.ipc');
const registerDraftSaleReturns = require('./draftSaleReturns.ipc');
const registerEmployees = require('./employees.ipc');
const registerExpenses = require('./expenses.ipc');
const registerGroupAccounts = require('./groupAccounts.ipc');
const registerProducts = require('./products.ipc');
const registerProductColors = require('./productColors.ipc');
const registerPurchases = require('./purchases.ipc');
const registerPurchaseReturns = require('./purchaseReturns.ipc');
const registerReceipts = require('./receipts.ipc');
const registerRegions = require('./regions.ipc');
const registerReports = require('./reports.ipc');
const registerSalaryRuns = require('./salaryRuns.ipc');
const registerSaleBills = require('./saleBills.ipc');
const registerSaleReturns = require('./saleReturns.ipc');
const registerStages = require('./stages.ipc');
const registerStock = require('./stock.ipc');
const registerStores = require('./stores.ipc');
const registerSubCustomers = require('./subCustomers.ipc');
const registerTransfers = require('./transfers.ipc');
const registerSettlements = require('./settlements.ipc');
const registerJournalVouchers = require('./journalVouchers.ipc');
const registerDeposits = require('./deposits.ipc');
const registerUpdates = require('./updates.ipc');
const registerVendors = require('./vendors.ipc');
const registerWageRuns = require('./wageRuns.ipc');
const registerZoom = require('./zoom.ipc');

module.exports = function registerIpcHandlers() {
  registerAccounts();
  registerAccountClasses();
  registerAlerts();
  registerAuth();
  registerAddas();
  registerBackup();
  registerBankAccounts();
  registerBusinessAccounts();
  registerCategories();
  registerChartAccounts();
  registerCheques();
  registerCities();
  registerCustomers();
  registerDraftPurchases();
  registerDraftPurchaseReturns();
  registerDraftExpenses();
  registerDraftReceipts();
  registerDraftSaleBills();
  registerDraftSaleReturns();
  registerEmployees();
  registerExpenses();
  registerGroupAccounts();
  registerProducts();
  registerProductColors();
  registerPurchases();
  registerPurchaseReturns();
  registerReceipts();
  registerRegions();
  registerReports();
  registerSalaryRuns();
  registerSaleBills();
  registerSaleReturns();
  registerStages();
  registerStock();
  registerStores();
  registerSubCustomers();
  registerTransfers();
  registerSettlements();
  registerJournalVouchers();
  registerDeposits();
  registerUpdates();
  registerVendors();
  registerWageRuns();
  registerZoom();
};
